;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-semi&comma
        coffee-dedent-line-backspace
        comment-dwim
        dabbrev-expand
        down-list
        end-of-buffer
        forward-sexp
        indent-for-tab-command
        indent-new-comment-line
        kill-region
        kill-sexp
        lisp-eval-last-sexp
        mark-sexp
        markdown-cycle
        markdown-exdent-or-delete
        paredit-backward
        paredit-backward-barf-sexp
        paredit-backward-kill-word
        paredit-backward-slurp-sexp
        paredit-backward-up
        paredit-comment-dwim
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-join-sexps
        paredit-kill
        paredit-meta-doublequote
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-raise-sexp
        paredit-reindent-defun
        paredit-semicolon
        paredit-splice-sexp
        paredit-wrap-round
        rebase-mode-fixup
        sgml-close-tag
        sgml-slash
        transpose-sexps
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        eval-expression
        helm-M-x
        helm-confirm-and-exit-minibuffer
        magit-status
        set-rectangular-region-anchor
        smex
        ))
